stages:
  - build
  - deploy


build_image_dev:
  interruptible: true
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  stage: build
  tags: [docker]
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
   - cat $docker_hub > /kaniko/.docker/config.json
   - /kaniko/executor
      --context .
      --dockerfile=Dockerfile
      --destination fefuboard/amelia-issues-backend-dev:latest


# deploy_job:
#   stage: deploy
#   image: docker
#   tags: [cloud2]
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#     DOCKER_TLS_VERIFY: 1
#     DOCKER_HOST: "tcp://89.169.147.75:2376"
#     DOCKER_CERT_PATH: /cert
#   # before_script:
#   # # - mv $ENV .env
#   # # - chmod og= $CLOUD2_KEY
#   # - mkdir -p /cert && mv $DOCKER_CA_CLOUD2 /cert/ca.pem && mv $DOCKER_KEY_CLOUD2 /cert/key.pem  && mv $DOCKER_CERT_CLOUD2  /cert/cert.pem
#   # - ls /cert
#   script:
#   # - ping 89.169.147.75
#   # - chmod 400 /cert/key.pem
#   # - docker --tlsverify  ps -a
#   - docker compose --tlsverify  -f docker-compose.yaml up -d

deploy_job:
  stage: deploy
  image: docker:24.0.5
  tags: [docker]
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  before_script:
    - apk update && apk add openssh-client
    - echo $ID_RSA
    - echo "SSH setup complete"s
  script:
    - echo "Deploy job"
    - chmod 400 /builds/parhom/amelia-issues-sync-data.tmp/ID_RSA
    - eval "$(ssh-agent -s)"
    - ssh-add /builds/parhom/amelia-issues-sync-data.tmp/ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SSH_USER@$HOST_CLOUD2 "
      pwd && ls -la &&
      echo '$DOCKERHUB_PAS' | docker login -u fefuboard --password-stdin &&
      cd /home/kozlovis/amelia-issues-dev &&
      docker compose up -d --force-recreate
      "

