"""status percentage_completion

Revision ID: e17a256d593c
Revises: 28656908dd1c
Create Date: 2024-03-06 11:34:31.389074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17a256d593c'
down_revision: Union[str, None] = '28656908dd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('percentage_completion', sa.Integer(), nullable=True))
    op.drop_column('statuses', 'percentage_complition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('percentage_complition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('statuses', 'percentage_completion')
    # ### end Alembic commands ###
