"""add cascades to issues - status history

Revision ID: 91c958b27059
Revises: 5290b54a06d1
Create Date: 2024-03-13 16:29:26.646463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c958b27059'
down_revision: Union[str, None] = '5290b54a06d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statuses_history_issue_id_fkey', 'statuses_history', type_='foreignkey')
    op.create_foreign_key(None, 'statuses_history', 'issues', ['issue_id'], ['external_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses_history', type_='foreignkey')
    op.create_foreign_key('statuses_history_issue_id_fkey', 'statuses_history', 'issues', ['issue_id'], ['external_id'])
    # ### end Alembic commands ###
