"""change lat long to float

Revision ID: bdd3b1b8ca0d
Revises: 8bcdec8c4b61
Create Date: 2024-03-06 22:21:29.534619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd3b1b8ca0d'
down_revision: Union[str, None] = '8bcdec8c4b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'latitude')
    op.drop_column('buildings', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('longitude', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('latitude', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
