"""add facility fk from work category to facility

Revision ID: 8f770815be1a
Revises: 6272375d40af
Create Date: 2024-03-06 17:00:06.017264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f770815be1a'
down_revision: Union[str, None] = '6272375d40af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_categories', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.alter_column('work_categories', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'work_categories', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_categories', type_='foreignkey')
    op.alter_column('work_categories', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('work_categories', 'facility_id')
    # ### end Alembic commands ###
