"""unset optional declarer id in issues

Revision ID: 2094f27593d4
Revises: 58001a7676ec
Create Date: 2024-03-13 14:44:09.558948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2094f27593d4'
down_revision: Union[str, None] = '58001a7676ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
