"""add facility id in floor

Revision ID: 091f0bea4e40
Revises: 24fc09346dff
Create Date: 2024-03-06 23:12:52.356571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091f0bea4e40'
down_revision: Union[str, None] = '24fc09346dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'floors', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.drop_column('floors', 'facility_id')
    # ### end Alembic commands ###
