"""remove additional services and additionla service

Revision ID: ff9aeb3407d5
Revises: 143e53edb723
Create Date: 2024-03-07 14:26:29.975969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff9aeb3407d5'
down_revision: Union[str, None] = '143e53edb723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_additional_service_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'additional_services_ids')
    op.drop_column('users', 'additional_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_service', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('additional_services_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.create_foreign_key('users_additional_service_fkey', 'users', 'services', ['additional_service'], ['id'])
    # ### end Alembic commands ###
