"""add tech passport

Revision ID: 6f18c81d016d
Revises: 6ca4ac2debca
Create Date: 2024-03-26 00:21:25.528238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f18c81d016d'
down_revision: Union[str, None] = '6ca4ac2debca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms_tech_passports')
    op.create_foreign_key(None, 'issues', 'users', ['executor_id'], ['id'])
    op.create_foreign_key(None, 'issues', 'users', ['declarer_id'], ['id'])
    op.create_foreign_key(None, 'issues', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'rooms', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_table('rooms_tech_passports',
    sa.Column('object_view', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('object_class', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('object_type', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('structural_unit', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('square', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institute_school_provost_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='rooms_tech_passports_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rooms_tech_passports_pkey'),
    sa.UniqueConstraint('external_id', name='rooms_tech_passports_external_id_key')
    )
    # ### end Alembic commands ###
