"""add foreign keys from rooms to facility and company

Revision ID: 143e53edb723
Revises: 091f0bea4e40
Create Date: 2024-03-07 10:57:16.365404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143e53edb723'
down_revision: Union[str, None] = '091f0bea4e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'facilities', ['facility_id'], ['id'])
    op.create_foreign_key(None, 'rooms', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'company_id')
    op.drop_column('rooms', 'facility_id')
    # ### end Alembic commands ###
