"""disable facility id

Revision ID: 2d355349f6ce
Revises: 957f07d4ab6c
Create Date: 2024-03-11 01:28:55.070054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d355349f6ce'
down_revision: Union[str, None] = '957f07d4ab6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issues_facility_id_fkey', 'issues', type_='foreignkey')
    op.drop_column('issues', 'facility_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('issues_facility_id_fkey', 'issues', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###
