"""add working column

Revision ID: 483decf8d118
Revises: ff9aeb3407d5
Create Date: 2024-03-07 14:44:35.081814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483decf8d118'
down_revision: Union[str, None] = 'ff9aeb3407d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('working', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'working')
    # ### end Alembic commands ###
