"""nullable columns for tech passport 

Revision ID: d46abe31a001
Revises: 6f18c81d016d
Create Date: 2024-03-26 00:52:06.423281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46abe31a001'
down_revision: Union[str, None] = '6f18c81d016d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tech_passports', 'object_view',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    op.alter_column('tech_passports', 'object_type',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    op.alter_column('tech_passports', 'object_class',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    op.alter_column('tech_passports', 'organization_3lvl',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tech_passports', 'organization_3lvl',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    op.alter_column('tech_passports', 'object_class',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    op.alter_column('tech_passports', 'object_type',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    op.alter_column('tech_passports', 'object_view',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    # ### end Alembic commands ###
