"""add email column

Revision ID: 87ca7d858adc
Revises: 3b7e37a833e4
Create Date: 2024-03-11 09:53:21.316061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ca7d858adc'
down_revision: Union[str, None] = '3b7e37a833e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('email', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'email')
    # ### end Alembic commands ###
