"""change lat long to float

Revision ID: 24fc09346dff
Revises: bdd3b1b8ca0d
Create Date: 2024-03-06 22:21:41.639456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fc09346dff'
down_revision: Union[str, None] = 'bdd3b1b8ca0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'longitude')
    op.drop_column('buildings', 'latitude')
    # ### end Alembic commands ###
