"""add cascades to issues - status history

Revision ID: 5290b54a06d1
Revises: 19bc9d73d7eb
Create Date: 2024-03-13 16:20:42.423404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5290b54a06d1'
down_revision: Union[str, None] = '19bc9d73d7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
