"""add nullable for building address

Revision ID: 749657648080
Revises: 8f770815be1a
Create Date: 2024-03-06 17:42:51.013824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749657648080'
down_revision: Union[str, None] = '8f770815be1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'adress',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'adress',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    # ### end Alembic commands ###
