"""add facility fk to service

Revision ID: 6272375d40af
Revises: e17a256d593c
Create Date: 2024-03-06 15:10:30.724730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6272375d40af'
down_revision: Union[str, None] = 'e17a256d593c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'facility_id')
    # ### end Alembic commands ###
