"""empty message

Revision ID: db220c53fd59
Revises: 171052877e29
Create Date: 2024-08-05 00:56:25.259659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db220c53fd59'
down_revision: Union[str, None] = '171052877e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issues_room_id_fkey', 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key('issues_room_id_fkey', 'issues', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
