"""refactor history status remove user rel

Revision ID: f92febcaecbd
Revises: 760d51d33a11
Create Date: 2024-03-12 17:46:05.626022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92febcaecbd'
down_revision: Union[str, None] = '760d51d33a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('user', sa.String(length=350), nullable=False))
    op.drop_constraint('statuses_history_user_id_fkey', 'statuses_history', type_='foreignkey')
    op.drop_column('statuses_history', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('statuses_history_user_id_fkey', 'statuses_history', 'users', ['user_id'], ['id'])
    op.drop_column('statuses_history', 'user')
    # ### end Alembic commands ###
