"""rename address in building

Revision ID: 8bcdec8c4b61
Revises: 0a22021b530a
Create Date: 2024-03-06 17:48:08.682671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcdec8c4b61'
down_revision: Union[str, None] = '0a22021b530a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('address', sa.String(length=350), nullable=True))
    op.drop_column('buildings', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('adress', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('buildings', 'address')
    # ### end Alembic commands ###
