"""make declarer_id is optional

Revision ID: 7c23bb3fb3ff
Revises: 59bb6bdf153c
Create Date: 2024-03-19 14:46:43.245826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c23bb3fb3ff'
down_revision: Union[str, None] = '59bb6bdf153c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
