"""disable user_id in User

Revision ID: 957f07d4ab6c
Revises: c7d0d120029b
Create Date: 2024-03-11 01:06:09.619035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957f07d4ab6c'
down_revision: Union[str, None] = 'c7d0d120029b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issues_user_id_fkey', 'issues', type_='foreignkey')
    op.drop_column('issues', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('issues_user_id_fkey', 'issues', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
