"""set optional declarer id in issues

Revision ID: 58001a7676ec
Revises: 62de9eff4009
Create Date: 2024-03-13 14:42:40.978705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58001a7676ec'
down_revision: Union[str, None] = '62de9eff4009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'declarer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
