"""add fk for building

Revision ID: 0a22021b530a
Revises: 749657648080
Create Date: 2024-03-06 17:46:33.799053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a22021b530a'
down_revision: Union[str, None] = '749657648080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'buildings', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'facility_id')
    # ### end Alembic commands ###
