"""change base and refactor history status

Revision ID: 760d51d33a11
Revises: 4de69b854ac3
Create Date: 2024-03-12 10:57:28.947642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760d51d33a11'
down_revision: Union[str, None] = '4de69b854ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('message', sa.String(), nullable=False))
    op.add_column('statuses_history', sa.Column('percentage', sa.Integer(), nullable=False))
    op.add_column('statuses_history', sa.Column('status', sa.String(length=350), nullable=False))
    op.add_column('statuses_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('statuses_history_status_id_fkey', 'statuses_history', type_='foreignkey')
    op.create_foreign_key(None, 'statuses_history', 'users', ['user_id'], ['id'])
    op.drop_column('statuses_history', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statuses_history', type_='foreignkey')
    op.create_foreign_key('statuses_history_status_id_fkey', 'statuses_history', 'statuses', ['status_id'], ['id'])
    op.drop_column('statuses_history', 'user_id')
    op.drop_column('statuses_history', 'status')
    op.drop_column('statuses_history', 'percentage')
    op.drop_column('statuses_history', 'message')
    # ### end Alembic commands ###
