"""rename finish date

Revision ID: 3b7e37a833e4
Revises: 2d355349f6ce
Create Date: 2024-03-11 02:19:30.626201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7e37a833e4'
down_revision: Union[str, None] = '2d355349f6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('finish_date_plane', sa.DateTime(), nullable=False))
    op.drop_column('issues', 'finish_date_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('finish_date_plan', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('issues', 'finish_date_plane')
    # ### end Alembic commands ###
