"""add optionality for priority_id

Revision ID: 4de69b854ac3
Revises: 87ca7d858adc
Create Date: 2024-03-12 09:58:41.951669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de69b854ac3'
down_revision: Union[str, None] = '87ca7d858adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
