"""empty message

Revision ID: 6a62eb2c28a0
Revises: acffe2eee528
Create Date: 2024-12-26 10:37:24.283484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a62eb2c28a0'
down_revision: Union[str, None] = 'acffe2eee528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('facility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'facilities', ['facility_id'], ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'facility_id')
    # ### end Alembic commands ###
