"""add unique constraints

Revision ID: 21a4a1d845b8
Revises: 54d511d0c0b6
Create Date: 2025-02-10 06:23:32.330728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a4a1d845b8'
down_revision: Union[str, None] = '54d511d0c0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'system_users', ['login'])
    op.create_unique_constraint(None, 'system_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_users', type_='unique')
    op.drop_constraint(None, 'system_users', type_='unique')
    # ### end Alembic commands ###
