"""make role title unique

Revision ID: d26ca0e4cf1d
Revises: 21a4a1d845b8
Create Date: 2025-02-14 01:33:09.404894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26ca0e4cf1d'
down_revision: Union[str, None] = '21a4a1d845b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
