"""add system_users roles permissions and rokes-permissions

Revision ID: ef5e34009bad
Revises: 3b631122edfa
Create Date: 2025-02-07 07:12:12.638403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5e34009bad'
down_revision: Union[str, None] = '3b631122edfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
