"""add disaabled to users

Revision ID: bf19b3c09155
Revises: d26ca0e4cf1d
Create Date: 2025-02-27 06:31:29.068083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf19b3c09155'
down_revision: Union[str, None] = 'd26ca0e4cf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_users', 'is_disabled')
    # ### end Alembic commands ###
