from app.repositories.building_repository import BuildingRepository
from app.repositories.company_repository import CompanyRepository
from app.repositories.facility_repository import FacilityRepository
from app.repositories.floor_repository import FloorRepository
from app.repositories.issue_repository import IssueRepository
from app.repositories.priority_repository import PriorityRepository
from app.repositories.room_repository import RoomRepository
from app.repositories.service_repository import ServiceRepository
from app.repositories.status_repository import StatusRepository
from app.repositories.statuses_history_repository import StatusHistoryRepository
from app.repositories.user_repository import UserRepository
from app.repositories.work_category_repository import WorkCategoryRepository
from app.repositories.workflow_repository import WorkflowRepository
from app.repositories.tech_possport_repository import TechPassportRepository

from app.repositories.system_user_repository import SystemUserRepository
from app.repositories.permissions.permission_repository import PermissionRepository
from app.repositories.permissions.role_permission_repository import RolePermissionRepository
from app.repositories.permissions.roles_repository import RoleRepository