stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Running build steps..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'


deploy_job:
  stage: deploy
  needs: [build_job]
  script:
    - echo "Deploy job"


