stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Running build steps..."


deploy_job:
  stage: deploy
  needs: 
    - build_job 
  script:
    - echo "Deploy jonb"


only:
  refs:
    -dev